# Configuração para carregar variáveis de ambiente
spring.config.import=optional:file:.env[.properties]

# Configurações da API Externa
external.api.base.url=${EXTERNAL_API_BASE_URL:https://api.iniciativaaplicativos.com.br/api}
external.api.token=${EXTERNAL_API_TOKEN:DEFAULT_TOKEN}
external.api.secret=${EXTERNAL_API_SECRET:DEFAULT_SECRET}

# Log para debug
logging.level.com.astralis.flow.stockflow_api.config=DEBUG